name: Build
on:
  push:


jobs:
  ci:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: "Install BuildX"
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: "Build docker image"
        uses: "docker/build-push-action@v2"
        with:
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
          build-args: "ARGUMENT=2"
